#!/bin/bash
# author: cgomesu

are_you_sure () {
	echo 'Please be aware that this tool will permanently OVERWRITE ALL the files listed in' $BAD_LOG 'from your system!'
	while [[ ! $response = 'y' && ! $response = 'n' ]]; do
		read -p 'Are you sure you want to continue? (y/n): ' response
	done
}

check_bad_log () {
	if [[ -z $BAD_LOG || ! -f $BAD_LOG ]]; then
		echo 'No log file was provided as argument or file does not exist.'
		end "Please provide the full path to a bad_flacs.log and try again." 1
	fi
}

start () {
	echo '#######################################'
	echo '######### BAD FLAC FIXER TOOL #########'
	echo '#######################################'
	echo '--------'
	echo 'This tool re-encodes flac files listed in a log file (e.g., bad_flacs.log) and overwrites'
	echo 'the existing file with the new encoding, wich can fix some of the issues with the original'
	echo 'file.  Regarding the log file, it is generated by the flac_diag.sh script but can also be'
	echo 'manually generated. If you want to manually generate the log file, make sure it has the'
	echo 'following structure:'
	echo '----- bad_flacs.log -----'
	echo '/full/path/to/file1.flac'
	echo '/full/path/to/file2.flac'
	echo '/full/path/to/file3.flac'
	echo '...'
	echo '/full/path/to/fileN.flac'
	echo '-------------------------'
}

# message then status
end () {
	echo '############################################'
	echo 'END OF THE SCRIPT'
	echo 'MESSAGE: '$1 
	echo '############################################'
	exit $2
}

interrupt () {
	echo '!! ATTENTION !!'
	echo 'Received a signal to stop the program right now.'
	echo '############################################'
	echo '############ SCRIPT INTERRUPTED ############'
	echo '############################################'
	exit 1
}

flac_fixer () {
	while read file; do
		if [[ -f $file && $file =~ (.flac$|.FLAC$) ]]; then
			echo '..............'
			echo 'Re-encoding file:' $file
			flac "$file" -fF
			echo 'Done. Now try playing the file again.'
			echo '..............'
		fi
	done < $BAD_LOG
}

# run tool
start
BAD_LOG=$1
check_bad_log

# ask user to confirm
are_you_sure
if [[ $response = 'n' ]]; then
	end "Better safe than sorry!" 0
fi
# start removal
echo '--------'
echo 'Starting fixer for the bad flac files...'
trap 'interrupt' SIGINT SIGHUP SIGTERM SIGKILL
flac_fixer
echo '--------'
if [[ $? -eq 0 ]]; then
	end "The script finished without errors." 0
fi
