#!/bin/bash
# author: cgomesu

are_you_sure () {
	echo 'Please be aware that this tool will permanently REMOVE ALL the files listed in' $BAD_LOG 'from your system!'
	while [[ ! $response = 'y' && ! $response = 'n' ]]; do
		read -p 'Are you sure you want to continue? (y/n): ' response
	done
}

check_bad_log () {
	if [[ -z $BAD_LOG || ! -f $BAD_LOG ]]; then
		echo 'No log file was provided as argument or file does not exist.'
		end "Please provide the full path to a bad_flacs.log and try again." 1
	fi
}

start () {
	echo '#########################################'
	echo '######### BAD FLAC REMOVAL TOOL #########'
	echo '#########################################'
	echo '--------'
	echo 'This tool deletes flac files listed in a log file (e.g., bad_flacs.log).'
	echo 'Such a log file is generated by the flac_diag.sh script but can also be manually generated.'
	echo 'If you want to manually generate the log file, make sure it has the following structure:'
	echo '----- bad_flacs.log -----'
	echo '/full/path/to/file1.flac'
	echo '/full/path/to/file2.flac'
	echo '/full/path/to/file3.flac'
	echo '...'
	echo '/full/path/to/fileN.flac'
	echo '-------------------------'
}

# message then status
end () {
	echo '############################################'
	echo 'END OF THE SCRIPT'
	echo 'MESSAGE: '$1 
	echo '############################################'
	exit $2
}

interrupt () {
	echo '!! ATTENTION !!'
	echo 'Received a signal to stop the program right now.'
	echo '############################################'
	echo '############ SCRIPT INTERRUPTED ############'
	echo '############################################'
	exit 1
}

flac_removal () {
	while read file; do
		if [[ -f $file ]]; then
			echo '..............'
			echo 'Deleting file:' $file
			rm -f "$file"
			echo 'Done.'
			echo '..............'
		fi
	done < $BAD_LOG
}

# run tool
start
BAD_LOG=$1
check_bad_log

# ask user to confirm
are_you_sure
if [[ $response = 'n' ]]; then
	end "Better safe than sorry!" 0
fi
# start removal
echo '--------'
echo 'Starting removal of the bad flac files...'
trap 'interrupt' SIGINT SIGHUP SIGTERM SIGKILL
flac_removal
echo '--------'
if [[ $? -eq 0 ]]; then
	end "The script finished without errors." 0
fi
